services:
  kanidm:
    image: kanidm/server:latest
    restart: unless-stopped
    volumes:
      - kanidm_data:/data:rw
      - ./config/${RTCNET_HOST:?error}:/config:ro
      - /var/lib/certs/idm:/cert:ro
    environment:
      KANIDM_CONFIG: /config/server.toml
    labels:
      traefik.enable: 'true'
      traefik.http.services.komodo.loadbalancer.server.port: '8443'
      traefik.http.services.komodo.loadbalancer.server.scheme: https
      traefik.http.services.komodo.loadbalancer.server.serverstransport: idm@file
      traefik.http.routers.komodo.rule: Host(`${RTCNET_HOST:?error}.idm.rtcid.ru`)
