services:
  prestart:
    image: alpine:latest
    restart: no
    volumes:
      - data:/data:rw
      - ./prestart.sh:/prestart.sh:ro
    command: /prestart.sh

  kanidm:
    image: kanidm/server:latest
    restart: unless-stopped
    user: 100:100
    depends_on:
      prestart:
        condition: service_completed_successfully
    volumes:
      - data:/data:rw
      - ./config/${RTCNET_HOST:?error}:/config:ro
      - /var/lib/certs/idm:/cert:ro
    environment:
      KANIDM_CONFIG: /config/server.toml
    labels:
      traefik.enable: 'true'
      traefik.http.services.komodo.loadbalancer.server.port: '8443'
      traefik.http.services.komodo.loadbalancer.server.scheme: https
      traefik.http.services.komodo.loadbalancer.serverstransport: idm@file
      traefik.http.routers.komodo.rule: Host(`${RTCNET_HOST:?error}.idm.rtcid.ru`)

networks:
  default:
    enable_ipv6: true
  
  traefik:
    external: true

volumes:
  data:
