services:
  bind:
    image: ubuntu/bind9:latest
    restart: unless-stopped
    ports:
      - 53:53/tcp
      - 53:53/udp
    volumes:
      - /var/lib/zones:/zones:ro
      - ./named.conf:/etc/bind/named.conf:ro
      - data:/var/lib/bind:rw
      - workdir:/var/cache/bind:rw

networks:
  default:
    enable_ipv6: true

volumes:
  data:
  workdir:
